on:
  schedule:
    - cron: '0 14 */1 * *'
  push:
    branches: main

name: Get Cansim

jobs:
  render:
    name: Get Cansim
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("tidyverse","cansim","rvest","gtrendsR"))'
      - name: Scrape the data
        run: Rscript february_briefing.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New Executive Order signed - data updated!' || echo "No changes to commit"
          git push origin || echo "No changes to commit"  
